"""Webhook resources for the MailChannels SDK."""

from .types import (
    SignatureParameters,
    Webhook,
    WebhookBatch,
    WebhookBatchDuration,
    WebhookBatchResult,
    WebhookBatchStatus,
    WebhookEvent,
    WebhookEventPayload,
    WebhookHeaders,
    WebhookPayload,
    WebhookPublicKey,
    WebhookValidationRequest,
    WebhookValidationResponse,
    WebhookValidationResult,
    WebhookValidationResults,
)
from .webhooks import (
    Webhooks,
    WebhooksResource,
    parse_signature_input,
    signature_is_fresh,
    signature_key_id,
    verify_content_digest,
)

__all__ = [
    "SignatureParameters",
    "Webhook",
    "WebhookBatch",
    "WebhookBatchDuration",
    "WebhookBatchResult",
    "WebhookBatchStatus",
    "WebhookEvent",
    "WebhookEventPayload",
    "WebhookHeaders",
    "WebhookPayload",
    "WebhookPublicKey",
    "WebhookValidationRequest",
    "WebhookValidationResponse",
    "WebhookValidationResult",
    "WebhookValidationResults",
    "Webhooks",
    "WebhooksResource",
    "parse_signature_input",
    "signature_is_fresh",
    "signature_key_id",
    "verify_content_digest",
]
